### ISSUE TITLE
 java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager

### ISSUE THREAD

**Issue by erichhartman** [corretto/corretto-8#165]
it  works well with jdk8u181 and openjdk （build 1.8.0_222）。
it doesn't work with corretto-8 on centos6 ，although i set headless true .It's ok on windows10.

I use following code to generate  verification code:

BufferedImage bim = new BufferedImage(width, height,
				BufferedImage.TYPE_BYTE_INDEXED);
		Graphics2D graphics = bim.createGraphics();
		Color c = getRandColor(200, 250);
		graphics.setColor(c);
		graphics.fillRect(0, 0, bim.getWidth(), bim.getHeight());
		graphics.setColor(Color.black);
		Font font = getFont();
		graphics.setFont(font);
		graphics.setColor(this.getRandColor());
		graphics.drawString(textCode, 8, 25);  // **exception: java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager**

java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
                at java.lang.Class.forName0(Native Method)
                at java.lang.Class.forName(Class.java:348)
                at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
                at java.security.AccessController.doPrivileged(Native Method)
                at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
                at java.awt.Font.getFont2D(Font.java:491)
                at java.awt.Font.access$000(Font.java:224)
                at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
                at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
                at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:669)
                at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:830)
                at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:50)
                at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
                at com.verifycode.VerifyCode.generateImageCode(VerifyCode.java:286)
                at com.verifycode.VerifyImage.doGet(VerifyImage.java:25)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by cliveverghese** [comment]
Hi @erichhartman 

Thank you for reporting this issue, We would like to take a look at this issue, Could you provide us with the details on how we could reproduce this issue? Also, How did you enable headless mode?

**Comment by davecurrie** [comment]
@erichhartman This is likely related to missing fontconfig on your system -- see #64 for more discussion. If you're using the RPM, this is slated to be fixed in the next Corretto release on 1/21.
Closing this issue in favor of #64
